[lint]
ignore = ["implicit_assignment", "duplicated_arguments"]
exclude = ["data-raw/"]
extend-select = ["TESTTHAT"]
check-roxygen = true
fix-roxygen = true

[lint.assignment]
operator = "<-"

[lint.quotes]
quote = "double"