[lint]
select = ["ALL"]
ignore = ["implicit_assignment", "duplicated_arguments"]
exclude = ["data-raw/"]
check-roxygen = true
fix-roxygen = true

[lint.assignment]
operator = "<-"

[lint.quotes]
quote = "double"
